# Generated by Django 3.0.3 on 2020-03-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200306_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='', help_text='Write the description of your Book here.', unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.TextField(default='sample_link', help_text='link to picture of book', unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(help_text='$', max_length=10, unique=True),
        ),
    ]
